clc;
clear;
close all;

tic;
I1 = Tiff('data/tn3.tif','r');
figure(1);
imshow(read(I1));
temp = rgb2gray(read(I1));
Ia2 = double(temp);
[matrvar] = varaloimopt(Ia2,8,17);
matrvar2=matrvar;
matrvar2(matrvar2<=31) = 0;
figure(2);
imshow(mat2gray(matrvar2));
title('No splicing originally and also correctly done by algorithm');
toc;

tic;
I1 = Tiff('data/fp5.tif','r');
figure(3);
imshow(read(I1));
temp = rgb2gray(read(I1));
Ia2 = double(temp);
[matrvar] = varaloimopt(Ia2,4,17);
matrvar2=matrvar;
matrvar2(matrvar2<=0.1) = 0;
figure(4);
imshow(mat2gray(matrvar2));
title('No splicing but shows the detection');
toc;

tic;
I1 = Tiff('data/tn4.tif','r');
figure(5);
imshow(read(I1));
temp = rgb2gray(read(I1));
Ia2 = double(temp);
[matrvar] = varaloimopt(Ia2,4,17);
matrvar2=matrvar;
matrvar2(matrvar2<=0.1) = 0;
figure(6);
imshow(mat2gray(matrvar2));
title('No splicing originally and also correctly done by algorithm');
toc;

tic;
I1 = Tiff('data/fp6.tif','r');
figure(7);
imshow(read(I1));
temp = rgb2gray(read(I1));
Ia2 = double(temp);
[matrvar] = varaloimopt(Ia2,8,17);
matrvar2=matrvar;
matrvar2(matrvar2<=0.1) = 0;
figure(8);
imshow(mat2gray(matrvar2));
title('No splicing but shows the detection');
toc;